### ISSUE TITLE
Ubuntu Installation

### ISSUE THREAD

**Issue by barnettjacob** [minrk/nbextension-scratchpad#4]
Hey, I'm trying to install the extension on a Linux box running Ubuntu 15.04

I get the error message below. Any ideas? Thanks in advance.
Jacob

```
Traceback (most recent call last):
  File "/home/jb/anaconda/bin/jupyter-nbextension", line 6, in <module>
    sys.exit(notebook.nbextensions.main())
  File "/home/jb/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/jb/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/home/jb/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 405, in start
    super(NBExtensionApp, self).start()
  File "/home/jb/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/jb/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 321, in start
    self.install_extensions()
  File "/home/jb/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 309, in install_extensions
    nbextensions_dir=self.nbextensions_dir,
  File "/home/jb/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 149, in install_nbextension
    ensure_dir_exists(nbext)
  File "/home/jb/anaconda/lib/python2.7/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/home/jb/anaconda/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/home/jb/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/share/jupyter'
```

**Comment by minrk** [comment]
If you want to do a single-user installation of this or any nbextension, add `--user`:

```
jupyter nbextension install --user nbextension-scratchpad
```

**Comment by barnettjacob** [comment]
Perfect. Thanks!!
